### ISSUE TITLE
ZIP有威胁？下载完被删除

### ISSUE THREAD

**Issue by tpaccount** [cqboyone/save_wechat_media#1]
win11 微软自带杀毒提示有威胁？下载完被删除

**Comment by cqboyone** [comment]
> win11 微软自带杀毒提示有威胁？下载完被删除

动作快点，在删除前去防火墙设置成允许。

**Comment by cqboyone** [comment]
> win11 微软自带杀毒提示有威胁？下载完被删除

可以去[smallevilbeast/ntchat](https://github.com/smallevilbeast/ntchat)提下issues
